version: "3.7"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker_config/Dockerfile
    command: bash -c "venv/bin/python3 portfolio/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - docker_config/env.dev
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14
    volumes:
      - ${DB_PATH}postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DB_NAME}
    ports:
      - 5432:5432
volumes:
  postgres_data:
    external: true



