version: "3.7"

services:
  web:
    image: cugehock/portfolio:server-v1.0
    container_name: web
    build:
      context: .
      dockerfile: ./docker_config/Dockerfile
    command: bash -c "venv/bin/gunicorn --chdir /usr/src/app/portfolio portfolio.wsgi:application -c /usr/src/app/gunicorn.conf.py"
    volumes:
      - static_volume:/usr/src/app/portfolio/static/
    environment:
      SECRETS_FILE: /run/secrets/portfolio_secrets
    secrets:
      - portfolio_secrets
    expose:
      - 8000
    env_file:
      - docker_config/env.prod
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    ports:
      - 5432:5432
  nginx:
    image: cugehock/portfolio:nginx-v1.0
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/static/
    depends_on:
      - web
volumes:
  static_volume:
  postgres_data:
secrets:
  portfolio_secrets:
    file: ./portfolio_secrets
  postgres_password:
    file: ./postgres_password
  postgres_user:
    file: ./postgres_user