version: "3.7"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker_config/Dockerfile
#    command: bash -c "venv/bin/python3 portfolio/manage.py runserver 0.0.0.0:8000"
    command: bash -c "venv/bin/gunicorn --chdir /usr/src/app/portfolio portfolio.wsgi:application -c /usr/src/app/gunicorn.conf.py"
    volumes:
      - static_volume:/usr/src/app/portfolio/static/
    expose:
      - 8000
    env_file:
      - docker_config/env.dev
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14
    volumes:
      - ${DB_VOLUME_NAME}:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DB_NAME}
    ports:
      - 5432:5432
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/static/
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:



