version: "3.7"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker_config/Dockerfile
    command: bash -c "venv/bin/gunicorn --chdir /usr/src/app/portfolio portfolio.wsgi:application -c /usr/src/app/gunicorn.conf.py"
    volumes:
      - static_volume:/usr/src/app/portfolio/static/
    expose:
      - 8000
    env_file:
      - docker_config/env.prod
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/static/
    depends_on:
      - web
volumes:
  static_volume:
