# Generated by Django 3.0.3 on 2020-06-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('level', models.IntegerField(choices=[(1, 'Entry'), (2, 'Middle'), (3, 'Confident'), (4, 'Fluent'), (5, 'Pro')], default=1)),
            ],
        ),
    ]
