# Generated by Django 3.0.3 on 2020-07-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='skill_images/'),
        ),
    ]
