# Generated by Django 3.0.3 on 2020-08-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200803_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
