# Generated by Django 3.0.3 on 2020-09-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200827_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.Skill'),
            preserve_default=False,
        ),
    ]
