# Generated by Django 3.0.3 on 2021-01-09 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_comment_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.CreateModel(
            name='SkillCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(1, 'Entry'), (2, 'Middle'), (3, 'Confident'), (4, 'Fluent'), (5, 'Pro')], default=1)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='main_app.Skill')),
            ],
        ),
    ]
