# Generated by Django 4.0.3 on 2022-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(choices=[(1, 'Entry'), (2, 'Middle'), (3, 'Confident'), (4, 'Fluent'), (5, 'Pro')], default=1),
        ),
    ]
