# Generated by Django 4.0.3 on 2022-05-12 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 8, 49, 6, 114220, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
