# Generated by Django 4.0.4 on 2022-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_project_text_alter_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.IntegerField(choices=[(1, 'Frontend'), (2, 'Backend'), (3, 'DevOps'), (4, 'Testing tools')], default=2),
        ),
        migrations.AddField(
            model_name='skill',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
