# Generated by Django 4.0.4 on 2022-07-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_skill_category_skill_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillCharacteristic',
        ),
    ]
